export { default as About } from './About';
export { default as Innovation } from './Innovation';
export { default as Landing } from './Landing';
export { default as Marketing } from './Marketing';
export { default as Overview } from './Overview';
export { default as SocialMedia } from './SocialMedia';
export { default as Education } from './Education';
export { default as Program } from './Program';
export { default as Feedback } from './Feedback';